version: '3.9'


services:
  db:
    image: postgres:14.6
    container_name: transactions_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    expose:
      - "5432"
  web:
    build:
      dockerfile: Dockerfile
      context: .
    image: transactions_docker:latest
    container_name: transactions-rest
    command: >
      bash -c "./manage.py migrate && ./manage.py add_crypto_data && ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_volume:/transactions_project/static
      - media_volume:/transactions_project/media
      - .:/transactions_project
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db


volumes:
  static_volume:
  media_volume:
  postgres_data: