# Generated by Django 4.2.3 on 2023-07-06 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название криптовалюты')),
            ],
            options={
                'verbose_name': 'Cryptocurrency',
                'verbose_name_plural': 'Cryptocurrenies',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Блокчейн-сеть')),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Networks',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_adress', models.CharField(max_length=255)),
                ('recipient_adress', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_adress', models.CharField(max_length=255)),
                ('sub_account_id', models.CharField(max_length=10)),
                ('cryptocurrency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='transactions.cryptocurrency')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='transactions.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Account',
                'verbose_name_plural': 'Service Accounts',
            },
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currencies', to='transactions.network', verbose_name='Блокчейн-сеть'),
        ),
    ]
