# Generated by Django 4.2.3 on 2023-07-06 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Блокчейн-сеть'),
        ),
    ]
