# Generated by Django 4.2.3 on 2023-07-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_created_at_alter_network_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Cryptocurrency name'),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currencies', to='transactions.network', verbose_name='Blockchain network'),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Blockchain network'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='cryptocurrency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='transactions.cryptocurrency', verbose_name='Cryptocurrency'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='transactions.network', verbose_name='Blockchain network'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='sub_account_id',
            field=models.CharField(max_length=10, verbose_name='subaccountID'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='wallet_adress',
            field=models.CharField(max_length=255, verbose_name='Wallet Address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Transaction created'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recipient_adress',
            field=models.CharField(max_length=255, verbose_name='Recipient Wallet Adress'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_adress',
            field=models.CharField(max_length=255, verbose_name='Sender Wallet Adress'),
        ),
    ]
