# Generated by Django 4.2.3 on 2023-07-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_sender_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='Cryptocurrency name'),
        ),
        migrations.AlterField(
            model_name='serviceaccount',
            name='wallet_adress',
            field=models.CharField(max_length=255, unique=True, verbose_name='Wallet Address'),
        ),
    ]
