# Generated by Django 4.2.3 on 2023-07-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('CANCELED', 'Canceled'), ('ACCEPTED', 'Accepted')], default='PROCESSING', editable=False, max_length=10, verbose_name='Transaction status'),
        ),
    ]
