# Generated by Django 4.2.3 on 2023-07-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_transaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceaccount',
            old_name='wallet_adress',
            new_name='wallet_address',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipient_adress',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_adress',
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_address',
            field=models.CharField(default='1231wqeew', max_length=255, verbose_name='Recipient Wallet Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_address',
            field=models.CharField(default='qweqwe1', max_length=255, verbose_name='Sender Wallet Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('CANCELED', 'Canceled'), ('ACCEPTED', 'Accepted')], default='PROCESSING', max_length=10, verbose_name='Transaction status'),
        ),
    ]
